server:
  port: 7000

spring:
  application:
    name: gulimail-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI4G3ewgWMxsrnaaeDuT1B
      secret-key: Kdk4YLfj0prQOfPHzzQf9sIbdD0YeV
      oss:
        endpoint: oss-cn-qingdao.aliyuncs.com
        bucket: gulimall-clouds
