server:
  port: 8887
spring:
  application:
    name: gulimail-gateway
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
#   测试连接  http://localhost:8887/?url=baidu
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
#测试连接  http://localhost:8887/?url=qq
        - id: test_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: admin_route
          uri: lb://renren-fast # 路由给renren-fast，lb代表负载均衡
          predicates:
            - Path=/api/** # 默认前端项目都带上api前缀，
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment} # 重写url
